-- ===========================================================================
--  PAIPAY DATALOGGER — ESQUEMA DE LA BASE PRINCIPAL (Neon / PostgreSQL)
--
--  Proyecto ESPOL PG15-PY26-04
--  "Acuicultura y TICs: Expansión Tecnológica en el Cantón Santa Lucía y Daule"
--  Componente: Aplicación Móvil con Sincronización Diferida (Java)
--
--  Ejecutar en el SQL Editor de la consola de Neon (console.neon.tech),
--  sobre la base neondb, esquema public, en la MISMA rama (branch) donde se
--  habilitó la Data API.
--
--  IMPORTANTE: la app se conecta con un JWT emitido por Neon Auth. La función
--  auth.user_id() devuelve el identificador del usuario que hizo la petición;
--  es la pieza que permite saber QUIÉN registró cada dato sin que la app tenga
--  que enviarlo (y sin que pueda falsearlo).
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. PERFIL DEL PRODUCTOR
--    Las credenciales las administra Neon Auth. Esta tabla solo guarda la
--    información propia del proyecto asociada a cada usuario.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.perfil_productor (
    user_id   TEXT PRIMARY KEY DEFAULT (auth.user_id()),
    nombre    TEXT NOT NULL,
    comuna    TEXT DEFAULT 'Paipayales',
    rol       TEXT NOT NULL DEFAULT 'PRODUCTOR'
              CHECK (rol IN ('PRODUCTOR','ESTUDIANTE','TECNICO','ADMIN')),
    activo    BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 2. CATÁLOGO DE PISCINAS Y LECHOS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.piscina (
    codigo   TEXT PRIMARY KEY,
    nombre   TEXT NOT NULL,
    area_m2  NUMERIC(10,2),
    activa   BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- 3. BIOMETRÍA DE PECES  (fuente: IN SITU)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.registro_biometria (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Clave natural generada en el teléfono: hace idempotente la sincronización
    uuid                 UUID          NOT NULL UNIQUE,
    -- Se rellena solo con el dueño del JWT: la app no puede suplantar a nadie
    user_id              TEXT          NOT NULL DEFAULT (auth.user_id()),
    fecha_muestreo       DATE          NOT NULL,
    -- Muestreo al que pertenece el pez: todos los medidos el mismo día.
    -- GENERATED ALWAYS: lo calcula Postgres, la app no lo envía. Es la forma de
    -- garantizar que el muestreo que ve el productor y el que ve el análisis
    -- sean el mismo, sin depender de que el teléfono lo calcule bien.
    codigo_muestreo      TEXT GENERATED ALWAYS AS
                         ('M-' || to_char(fecha_muestreo, 'DDMMYYYY')) STORED,
    piscina              TEXT          NOT NULL,
    -- UNA FILA = UN PEZ. Antes había un cantidad_muestreada que obligaba a
    -- promediar en campo; sin medidas individuales no hay dispersión, y sin
    -- dispersión el factor de condición promedio engaña.
    peso_g               NUMERIC(10,2) NOT NULL CHECK (peso_g > 0),
    talla_cm             NUMERIC(10,2) NOT NULL CHECK (talla_cm > 0),
    factor_condicion     NUMERIC(10,3),
    observacion          TEXT,
    registrado_por       TEXT,
    creado_en            TIMESTAMPTZ   NOT NULL,
    sincronizado_en      TIMESTAMPTZ,
    recibido_en          TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_biometria_piscina_fecha
    ON public.registro_biometria (piscina, fecha_muestreo);

COMMENT ON COLUMN public.registro_biometria.factor_condicion
    IS 'K de Fulton = 100 * peso(g) / talla(cm)^3, calculado en el dispositivo.';
COMMENT ON COLUMN public.registro_biometria.creado_en
    IS 'Momento real de la captura en campo.';
COMMENT ON COLUMN public.registro_biometria.recibido_en
    IS 'Momento en que el dato llegó al servidor. La diferencia con creado_en mide el desfase de la sincronización diferida.';

-- ---------------------------------------------------------------------------
-- 4. CALIDAD DE AGUA  (fuente: IN SITU) — alimenta el Semáforo de Alertas
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.registro_agua (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            UUID         NOT NULL UNIQUE,
    user_id         TEXT         NOT NULL DEFAULT (auth.user_id()),
    fecha_muestreo  DATE         NOT NULL,
    piscina         TEXT         NOT NULL,
    -- El pH no es un parámetro más: decide qué fracción del amonio está en su
    -- forma tóxica (NH3). Por eso es obligatorio.
    ph              NUMERIC(4,2) NOT NULL CHECK (ph BETWEEN 0 AND 14),
    -- Ciclo del nitrógeno: los peces excretan AMONIO, las bacterias lo oxidan
    -- a NITRITO y este a NITRATO. Los dos primeros son tóxicos.
    amonio_mg_l     NUMERIC(8,3) NOT NULL CHECK (amonio_mg_l >= 0),
    nitrito_mg_l    NUMERIC(8,3) NOT NULL CHECK (nitrito_mg_l >= 0),
    nitrato_mg_l    NUMERIC(8,2) NOT NULL CHECK (nitrato_mg_l >= 0),
    -- Peces estimados. Opcional: no se cuenta en cada muestreo, pero cuando
    -- está permite detectar mortalidad comparando con el muestreo anterior.
    poblacion_estimada INTEGER   CHECK (poblacion_estimada >= 0),
    -- Estado del semáforo calculado en el dispositivo
    estado_alerta   TEXT CHECK (estado_alerta IN ('SIN_DATO','VERDE','AMARILLO','ROJO')),
    observacion     TEXT,
    registrado_por  TEXT,
    creado_en       TIMESTAMPTZ  NOT NULL,
    sincronizado_en TIMESTAMPTZ,
    recibido_en     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_agua_piscina_fecha
    ON public.registro_agua (piscina, fecha_muestreo DESC);
CREATE INDEX IF NOT EXISTS ix_agua_estado
    ON public.registro_agua (estado_alerta);

-- ---------------------------------------------------------------------------
-- 5. ENSAYOS DE LABORATORIO  (fuente: LABORATORIO) — Consolidación de Fuentes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ensayo_laboratorio (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            UUID          NOT NULL UNIQUE,
    user_id         TEXT          NOT NULL DEFAULT (auth.user_id()),
    fecha_muestreo  DATE          NOT NULL,
    piscina         TEXT          NOT NULL,
    codigo_muestra  TEXT,
    tipo_muestra    TEXT          NOT NULL,
    parametro       TEXT          NOT NULL,
    valor           NUMERIC(14,4) NOT NULL,
    unidad          TEXT,
    laboratorio     TEXT,
    observacion     TEXT,
    registrado_por  TEXT,
    creado_en       TIMESTAMPTZ   NOT NULL,
    sincronizado_en TIMESTAMPTZ,
    recibido_en     TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_lab_piscina_fecha
    ON public.ensayo_laboratorio (piscina, fecha_muestreo);
CREATE INDEX IF NOT EXISTS ix_lab_parametro
    ON public.ensayo_laboratorio (parametro);
